name: Test Ubuntu Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: System Info
        shell: bash
        run: |
          echo "=============================="
          echo "OS"
          echo "=============================="
          cat /etc/os-release

          echo
          echo "=============================="
          echo "CPU"
          echo "=============================="
          nproc
          lscpu

          echo
          echo "=============================="
          echo "RAM"
          echo "=============================="
          free -h

          echo
          echo "=============================="
          echo "DISK"
          echo "=============================="
          df -hT

          echo
          echo "=============================="
          echo "BLOCK DEVICES"
          echo "=============================="
          lsblk -o NAME,SIZE,FSTYPE,MOUNTPOINTS

          echo
          echo "=============================="
          echo "ROOT FREE SPACE"
          echo "=============================="
          df -h /

          echo
          echo "=============================="
          echo "/mnt"
          echo "=============================="
          df -h /mnt 2>/dev/null || true

          echo
          echo "=============================="
          echo "Docker"
          echo "=============================="
          docker --version || true
